
const NotificationData = [
  {
    id: '1',
    tag: 'Booking Update',
    status: 'Accepted',
    message: 'Your booking with Glamour Salon for haircut on October 26, 2024 has been accepted',
    vendor: 'Vendor: Glamour Salon',
    service: 'Service: Haircut',
    reason: null,
    time: '2 hours ago',
    isRead: false,
  },
  {
    id: '2',
    tag: 'General Message',
    status: null,
    message: 'New feature: Virtual Consultations are now live! Explore personalized beauty advice from experts.',
    vendor: null,
    service: null,
    reason: null,
    time: '5 hours ago',
    isRead: false,
  },
  {
    id: '3',
    tag: 'Booking Update',
    status: 'Declined',
    message: 'Your booking with Serene Spa for Massage on October 25, 2024 has been declined.',
    vendor: 'Vendor: Serene Spa',
    service: 'Service: Massage',
    reason: 'Reason: Fully booked',
    time: '1 day ago',
    isRead: true,
  },
  {
    id: '4',
    tag: 'Promotion',
    status: null,
    message: 'Exclusive offer: Get 20% off your next facial at Pure Beauty Studio this week.',
    vendor: null,
    service: null,
    time: '3 days ago',
    isRead: false,
  },
   {
    id: '5',
    tag: 'General Message',
    status: null,
    message: 'Update : Our privacy policy has been revised. Please review the changes at your convinence.',
    vendor: null,
    service: null,
    reason: null,
    time: '1 week ago',
    isRead: true,
  },
  {
    id: '6',
    tag: 'Booking Update',
    status: 'Accepted',
    message: 'Your booking with The Babershop for Beard Trim on October 20, 2024 has been accepted',
    vendor: ' Vendor: The Barbershop',
    service: 'Service: Beard Trim',
    reason: null,
    time: '1 week ago',
    isRead: true,
  },
  {
    id: '7',
    tag: 'General Message',
    status: null,
    message: 'Welcome to Glamstar! Get started by exploring services near you',
    vendor: null,
    service: null,
    time: '2 weeks ago',
    isRead: false,
  },

]

export default NotificationData
  
